
services:
  backend:
    build:
      context: .
      dockerfile: ./dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./.env

  frontend:
    build:
      context: .
      dockerfile: ./dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
