# Use a slim Python image
FROM python:3.12-slim as backend
WORKDIR /email-cleaner-app/

COPY . .

 RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /email-cleaner-app/backend
CMD ["python", "manage.py", "runserver"]



